language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "7"
  - "8"

script:
  - npm install
  - npm run lint

deploy:
  provider: script
  script: npm run build
  on:
    branch: master
