language: node_js

node_js:
  - "8"

script:
  - npm test

before_deploy:
  - npm run build -- --prefix-paths

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./public
  on:
    branch: master