language: node_js

node_js:
  - "8"

cache: yarn

before_script:
  - "yarn global add gatsby"

script:
  - "yarn test"

after_success:
  - "NODE_DEBUG=gh-pages npm run deploy"

branches:
  only:
    - master
